version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: exemplo_senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "3000:3000"
volumes:
  postgres_data:
